var originalNum = 23;
alert(originalNum);
var num = 10;
alert(num);
var popularNumber = num + 200;
alert(popularNumber);
var whatsLeftOver = 10 %3;
alert(whatsLeftOver);
 var num = 1;
 alert(num);
var newNum = ++num;
alert(newNum);
var totalCost = (1 + 3)*4;
alert(totalCost);
var resultOfComputation = (2 * 4) * 4 + 2;
alert(resultOfComputation);
 var message = "Thanks, ";
 var userName = "Susan";
 var banger = "!";
 var customMess= message + userName + banger;
alert(customMess);
 var question= "Your species?";
 alert(question);
var defaultAnswer= "human";
alert(defaultAnswer);
var spec = prompt(question, defaultAnswer);
alert(spec);
var numberOfCats= prompt("How many cats?");
alert(numberOfCats);
 var tooManyCats = numberOfCats+ 1;
 alert(tooManyCats);

