var originalNum = 23;
alert(originalNum);
var num = 10;
alert(num);
var popularNumber = num + 200;
alert(popularNumber);
var whatsLeftOver = 10 %3;
alert(whatsLeftOver);
 var num = 1;
 alert(num);
var newNum = ++num;
alert(newNum);